---
apiVersion: v1
kind: Pod
metadata:
  name: httpd
spec:
  containers:
    - name: httpddummuy
      image: httpd
      ports:
        - containerPort: 80
          name: bokklao port
          protocol: TCP
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
