#create 2 more init container and lets chech the functionlity and we have set the limits 
#but resouce crush we have deleted the limits and resouces
---
apiVersion: v1
kind: Pod
metadata: 
  name: trail6
spec:
  restartPolicy: OnFailure
  initContainers: 
    - name: init1
      image: alpine
      args:
        - sleep
        - 10s
    - name: init2
      image: alpine
      args:
        - sleep
        - 10s
    - name: init3
      image: alpine
      args:
        - sleep
        - 10s
  containers: 
    - name: nginx
      image: nginx
    - name: sidecar1
      image: alpine
      args:
        - sleep
        - 1d
  