---
apiVersion: v1
kind: Pod
metadata:
  name: httpd
spec:
  containers:
    - name: httpddummuy
      image: httpd
      ports:
        - containerPort: 80
          name: bokklao port
          protocol: TCP
    - name: httpddummuy
      image: httpd
      ports:
        - containerPort: 80
          name: bokklao port
          protocol: TCP