---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: trtrail1-rs
  labels:
    name: trail1
spec:
  minReadySeconds: 10
  replicas: 3
  selector: 
    matchLabels:
      app: nginx
  template:
    metadata:
      name: 
      labels: 
        app: nginx
        env: dev
        version: "1.0"
    spec:
      containers:
        - image: nginx
          name: nginx
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
  