---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spc-rs
  labels: 
    app: spc
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: spc
template:
  metadata:
    labels:
      app: spc
      env: dev
      version: v1.0 
  spec:
    restartPolicy: Always
    containers:
      - name: spcimage
        image: arifullalab01/spcimagedocker:new
        ports:
          - containerPort: 8080


