---
apiVersion: v1
kind: Service
metadata:
  name: spc-svc
spec: 
  type: NodePort
  selector:
      app: spc
  ports:
    - name: spc-svc
      port: 8080
      nodePort: 31000
      targetPort: 8080